`define ALU_OP 32
`define ADD    0
`define SUB    1
`define LT     2
`define LTU    3
`define AND    4
`define NOR    5
`define OR     6
`define XOR    7
`define SLL    8
`define SRL    9
`define SRA    10
`define LU12I  11
`define MEM_W_W 12
`define MEM_W_H 13
`define MEM_W_B 14
`define GR_WE  15
`define MEM_R_W 16
`define MEM_R_H 17
`define MEM_R_B 18
`define MEM_RSIGNAL 19
`define MUL    20
`define MULH   21
`define MULHU  22
`define DIV    23
`define DIVU   24
`define MOD    25
`define MODU   26             